Each Client can only access to its users + HAL
Maxime22/bilemo pull request #11
Opened 2021-06-29 11:08 UTC by Maxime22

2021-06-30 15:54 UTC, TBoileau requested changes

2021-06-30 15:54 UTC, TBoileau commented on composer.json
> +        "symfony/test-pack":"1.0.8"
Que fait le test-pack dans les dépendances pour la prod ?

2021-06-30 15:54 UTC, TBoileau commented on src/EventSubscriber/JWTSubscriber.php
> +}
Quelle est la raison de surcharger le contenu de ton token ?

2021-06-30 15:54 UTC, TBoileau commented on src/Serializer/ClientDenormalizer.php
> +}
Pourquoi ?

2021-06-30 17:01 UTC, Maxime22 commented on src/Serializer/ClientDenormalizer.php
> +}
Pour que les actions de User qui utilisent normalize correspondent au Client connecté

2021-06-30 17:09 UTC, Maxime22 commented on src/EventSubscriber/JWTSubscriber.php
> +}
Pour que je puisse faire $client->setId($id)->setUsername($payload['username']); dans createFromPayload
Puis $this->security->getUser()->getId() en appelant le composant security qui me renvoie le User Token

2021-07-05 07:28 UTC, TBoileau commented on src/EventSubscriber/JWTSubscriber.php
> +}
En quoi diminue-tg-il le nombre de requête ? Dans tous les cas il fait 1 requête, celle qui va chercher le client en BDD ?

2021-07-05 07:30 UTC, TBoileau commented on src/Serializer/ClientDenormalizer.php
> +}
Donc en gros, tu passes par la dénormalisation pour setter le client ? Pourquoi ici et pas ailleurs (listener, persister, ...) ?

2021-07-05 10:12 UTC, Maxime22 commented on src/Serializer/ClientDenormalizer.php
> +}
Bah j'ai fait comme grafikart me disait de faire, j'ai pas vraiment d'autres raisons spécifiques ^^

2021-07-05 10:16 UTC, Maxime22 commented on src/EventSubscriber/JWTSubscriber.php
> +}
Oui mais il refait pas cette requête à chaque fois qu'on demande une info à l'API, il se sert des infos dans le token plutôt que des infos dans la BDD
J'ai peut-être mal compris, c'est à 11:30 de cette vidéo : https://grafikart.fr/tutoriels/api-platform-auth-jwt-1915

2021-07-05 17:31 UTC, merged